name: Deploy OpenTelemetry Demo

on:
  workflow_dispatch: # Manual trigger for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy OpenTelemetry Demo
      run: |
        # Apply the YAML file directly using the pre-configured EKS client
        kubectl apply -f k8s/opentelemetry-demo.yaml

    - name: Verify Deployment
      run: |
        # Verify pods and services
        kubectl get pods
        kubectl get svc
